#
#   "Commons Clause" License, https://commonsclause.com/
#
#   The Software is provided to you by the Licensor under the License,
#   as defined below, subject to the following condition.
#
#   Without limiting other conditions in the License, the grant of rights
#   under the License will not include, and the License does not grant to
#   you, the right to Sell the Software.
#
#   For purposes of the foregoing, "Sell" means practicing any or all of
#   the rights granted to you under the License to provide to third parties,
#   for a fee or other consideration (including without limitation fees for
#   hosting or consulting/support services related to the Software), a
#   product or service whose value derives, entirely or substantially, from
#   the functionality of the Software. Any license notice or attribution
#   required by the License must also include this Commons Clause License
#   Condition notice.
#
#   Software:    NLPCraft
#   License:     Apache 2.0, https://www.apache.org/licenses/LICENSE-2.0
#   Licensor:    Copyright (C) NLPCraft. https://nlpcraft.org
#
#       _   ____      ______           ______
#      / | / / /___  / ____/________ _/ __/ /_
#     /  |/ / / __ \/ /   / ___/ __ `/ /_/ __/
#    / /|  / / /_/ / /___/ /  / /_/ / __/ /_
#   /_/ |_/_/ .___/\____/_/   \__,_/_/  \__/
#          /_/
#

title: NLPCraft
email: info@nlpcraft.org
copyright: Copyright (C) NLPCraft.
baseurl: ""
url: ""

twitter_username: nlpcraft
github_username:  nlpcraft

# Manually update to the latest version:
# ===================
latest_version: 0.8.2
java_client_latest_version: 0.4.0
# ===================

github: [metadata]

# SASS settings.
sass:
  sass_dir: _scss
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  blanklines: false
  profile: false
  startings: [html, head, body]

# Build settings.
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

